# Text Classification

In [170]:
import pandas as pd
import numpy as np
from glob import glob
from lyricscomfunc import dwnld_sng_txt, gen_corpus_labels
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

save some artist urls

In [171]:
mtlc_artist_url   = "https://www.lyrics.com/artist/Metallica/4906"
jhnmyr_artist_url = "https://www.lyrics.com/artist/John-Mayer/405816"
aild_artist_url   = "https://www.lyrics.com/artist/As-I-Lay-Dying/513658"

download song lyrics

In [172]:
#dwnld_sng_txt(jhnmyr_artist_url, 10, verb=True)

create lists for corpus(songtexts) and labels(artist names)

In [173]:
filepathlist = glob("../data/Artists/*/*.txt")

cor_lab_list = gen_corpus_labels(filepathlist)

In [174]:
#pd.DataFrame({"songtext": cor_lab_list[0], "artist": cor_lab_list[1]})

transform songtexts for ml algos

In [175]:
vctrzr = TfidfVectorizer(stop_words='english', ngram_range=(1,2), max_df=0.75)
X = vctrzr.fit_transform(cor_lab_list[0])

Xarr = X.toarray()
y = cor_lab_list[1].copy()

check if everything went as expected

In [176]:
df = pd.DataFrame(X.toarray(), 
                  columns=vctrzr.get_feature_names_out(), 
                  index=cor_lab_list[1])
#df
#np.square(df).sum(axis=1)

fit lr model make test prediction

In [177]:
new_song = ["electric"]

new_song_vctrzd = vctrzr.transform(new_song)

In [178]:
lr = LogisticRegression().fit(Xarr,y)

In [179]:
print(lr.score(Xarr,y))
print(lr.predict(new_song_vctrzd))
print(lr.predict_proba(new_song_vctrzd))

1.0
['Metallica']
[[0.30237085 0.28635233 0.41127682]]


fit rf model and make test prediction (doesn't work at all, probably overfitting massively)

In [180]:
rf = RandomForestClassifier(max_depth=3, max_features="sqrt", n_estimators=100).fit(Xarr,y)

In [181]:
print(rf.score(Xarr,y))
print(rf.predict(new_song_vctrzd))
print(rf.predict_proba(new_song_vctrzd))

1.0
['As_I_Lay_Dying']
[[0.42336767 0.29080258 0.28582975]]


fit naive bayes and make test pred

In [182]:
nb = MultinomialNB().fit(Xarr,y)

In [183]:
print(nb.score(Xarr,y))
print(nb.predict(new_song_vctrzd))
print(nb.predict_proba(new_song_vctrzd))

1.0
['Metallica']
[[0.286885   0.28566842 0.42744658]]


In [3]:
%%script echo skip

import numpy as np
from matplotlib import pyplot as plt
import wordcloud

mask = np.zeros((500, 500, 3), np.uint8)
mask[150:350,150:350,:] = 255  # masked out area

cloud = wordcloud.WordCloud(background_color="white",
                max_words=50,
                mask=mask,
                collocations=False,  # calculates frequencies
                contour_color='steelblue').generate("This this this this this this this is just a test")
                # stop words are removed!

plt.figure(figsize = (40,40))
plt.imshow(cloud, interpolation='bilinear')
plt.savefig('cloud.png')
plt.show()

skip
